name: build_license_collector
description: Collects licenses from your dependencies with build_runner
version: 2.0.0
repository: https://github.com/simolus3/build_license_collector

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  build: ^4.0.0
  build_modules: ^5.0.18
  cli_util: ^0.4.2
  glob: ^2.1.3
  graphs: ^2.3.2
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.14.4
  build_runner: ^2.4.14
  build_test: ^3.3.0
